services:
  frontend-svc:
    image: frontend-svc:latest
    build:
      context: ../FrontendService/FrontendServiceAPI
      dockerfile: Dockerfile
    container_name: frontend-svc
    ports:
      - "8080:80"
    networks:
      - auctionnet

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - auctionnet
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP (backend)
      - "15672:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - auctionnet
  
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - auctionnet
  
  vaulthost:
    image: hashicorp/vault:latest
    container_name: vaulthost
    restart: on-failure:10
    ports:
      - "8201:8201"
    environment:
      VAULT_ADDR: "https://0.0.0.0:8201"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8201", "tls_disable": "0", "tls_cert_file":"/data/cert.pem", "tls_key_file":"/data/key.pem"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}'
      VAULT_DEV_ROOT_TOKEN_ID: "00000000-0000-0000-0000-000000000000"
      VAULT_TOKEN: "00000000-0000-0000-0000-000000000000"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data:/data
      - vaultdataVOL:/var/lib/vault:rw
    healthcheck:
      retries: 5
    networks:
      - auctionnet
    command: server -dev -dev-root-token-id="00000000-0000-0000-0000-000000000000"

  vault-init:
    container_name: vault-init
    image: hashicorp/vault:latest
    command: sh "/app/vault_init.sh"
    depends_on:
      - vaulthost
    healthcheck:
      retries: 5
    volumes:
      - ./vault-init/vault_init.sh:/app/vault_init.sh
    networks:
      - auctionnet
  
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - auctionnet
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - auctionnet

networks:
  auctionnet:
    name: auctionnet
    external: false

volumes:
  mongodb_data_container:
  vaultdataVOL:
    external: false

